/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pos;

import javax.swing.JLayeredPane;
import javax.swing.JPanel;

/**
 *
 * @author Edwin
 */
public class Grocery extends javax.swing.JFrame {

   

    /**
     * Creates new form Grocery
     */
    public Grocery() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JButton();
        mainPanels = new javax.swing.JLayeredPane();
        registerPanel = new javax.swing.JPanel();
        unscannableItemsButtons = new javax.swing.JPanel();
        unscannableItemsLabel = new javax.swing.JLabel();
        produceButton = new javax.swing.JButton();
        fruitButton = new javax.swing.JButton();
        deliButton = new javax.swing.JButton();
        bakeryButton = new javax.swing.JButton();
        foodCourtButton = new javax.swing.JButton();
        bulkButton = new javax.swing.JButton();
        unscannableItemsPanels = new javax.swing.JLayeredPane();
        producePanel = new javax.swing.JPanel();
        cornButton = new javax.swing.JButton();
        potatoButton = new javax.swing.JButton();
        garlicButton = new javax.swing.JButton();
        broccoliButton = new javax.swing.JButton();
        carrotButton = new javax.swing.JButton();
        cucumberButton = new javax.swing.JButton();
        onionButton = new javax.swing.JButton();
        greenBeanButton = new javax.swing.JButton();
        lettuceButton = new javax.swing.JButton();
        spinachButton = new javax.swing.JButton();
        fruitPanel = new javax.swing.JPanel();
        appleButton = new javax.swing.JButton();
        orangeButton = new javax.swing.JButton();
        bananaButton = new javax.swing.JButton();
        grapesButton = new javax.swing.JButton();
        strawberriesButton = new javax.swing.JButton();
        cherriesButton = new javax.swing.JButton();
        pineappleButton = new javax.swing.JButton();
        watermelonButton = new javax.swing.JButton();
        kiwiButton = new javax.swing.JButton();
        mangoButton = new javax.swing.JButton();
        deliPanel = new javax.swing.JPanel();
        hamButton = new javax.swing.JButton();
        turkeyButton = new javax.swing.JButton();
        roastBeefButton = new javax.swing.JButton();
        salamiButton = new javax.swing.JButton();
        bolognaButton = new javax.swing.JButton();
        cheddarButton = new javax.swing.JButton();
        swissButton = new javax.swing.JButton();
        pepperJackButton = new javax.swing.JButton();
        mozzarellaButton = new javax.swing.JButton();
        goudaButton = new javax.swing.JButton();
        bakeryPanel = new javax.swing.JPanel();
        whiteLoafButton = new javax.swing.JButton();
        wheatLoafButton = new javax.swing.JButton();
        ryeLoafButton = new javax.swing.JButton();
        sourdoughLoafButton = new javax.swing.JButton();
        baguetteButton = new javax.swing.JButton();
        bagelButton = new javax.swing.JButton();
        rollsButton = new javax.swing.JButton();
        cookiesButton = new javax.swing.JButton();
        muffinButton = new javax.swing.JButton();
        cakeButton = new javax.swing.JButton();
        foodCourtPanel = new javax.swing.JPanel();
        pizzaSliceButton = new javax.swing.JButton();
        wholePizzaButton = new javax.swing.JButton();
        hotDogButton = new javax.swing.JButton();
        sandwichButton = new javax.swing.JButton();
        saladButton = new javax.swing.JButton();
        soupButton = new javax.swing.JButton();
        iceCreamButton = new javax.swing.JButton();
        churrosButton = new javax.swing.JButton();
        smallDrinkButton = new javax.swing.JButton();
        largeDrinkButton = new javax.swing.JButton();
        bulkPanel = new javax.swing.JPanel();
        oatsButton = new javax.swing.JButton();
        granolaButton = new javax.swing.JButton();
        peanutsButton = new javax.swing.JButton();
        almondsButton = new javax.swing.JButton();
        cashewsButton = new javax.swing.JButton();
        flourButton = new javax.swing.JButton();
        sugarButton = new javax.swing.JButton();
        trailMixButton = new javax.swing.JButton();
        driedFruitButton = new javax.swing.JButton();
        candyButton = new javax.swing.JButton();
        jPanelTotal = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        subTotalLabel = new javax.swing.JLabel();
        taxLabel = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lowerMenuPanel = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        managementPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        inventoryButton = new javax.swing.JButton();
        addItemButton = new javax.swing.JButton();
        registerEmployeeButton = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        inventoryPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLayeredPaneInventory = new javax.swing.JLayeredPane();
        lookItemPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        fixQuantityPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        addNewProductPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton15 = new javax.swing.JButton();
        registerEmployeePanel = new javax.swing.JPanel();
        labelPanel = new javax.swing.JPanel();
        firstLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        last = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        pass = new javax.swing.JLabel();
        passcodeTextField = new javax.swing.JTextField();
        SSN = new javax.swing.JLabel();
        ssnTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        birthTextField = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        discountPanel = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        loginArea = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        fillerLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        submitButton = new javax.swing.JButton();
        loginMessageLabel = new javax.swing.JLabel();
        logOutButton = new javax.swing.JButton();
        FrameMenuPanel = new javax.swing.JPanel();
        registerButton = new javax.swing.JButton();
        logInButton = new javax.swing.JButton();
        managementButton = new javax.swing.JButton();
        userInfoLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        logo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoActionPerformed(evt);
            }
        });

        mainPanels.setLayout(new java.awt.CardLayout());

        unscannableItemsButtons.setLayout(new java.awt.GridLayout(0, 1, 3, 3));

        unscannableItemsLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        unscannableItemsLabel.setForeground(new java.awt.Color(0, 0, 102));
        unscannableItemsLabel.setText("CATEGORIES");
        unscannableItemsButtons.add(unscannableItemsLabel);

        produceButton.setBackground(new java.awt.Color(255, 204, 0));
        produceButton.setText("PRODUCE");
        produceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produceButtonActionPerformed(evt);
            }
        });
        unscannableItemsButtons.add(produceButton);

        fruitButton.setBackground(new java.awt.Color(255, 204, 0));
        fruitButton.setText("FRUIT");
        fruitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fruitButtonActionPerformed(evt);
            }
        });
        unscannableItemsButtons.add(fruitButton);

        deliButton.setBackground(new java.awt.Color(255, 204, 0));
        deliButton.setText("DELI");
        deliButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliButtonActionPerformed(evt);
            }
        });
        unscannableItemsButtons.add(deliButton);

        bakeryButton.setBackground(new java.awt.Color(255, 204, 0));
        bakeryButton.setText("BAKERY");
        bakeryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bakeryButtonActionPerformed(evt);
            }
        });
        unscannableItemsButtons.add(bakeryButton);

        foodCourtButton.setBackground(new java.awt.Color(255, 204, 0));
        foodCourtButton.setText("FOOD COURT");
        foodCourtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodCourtButtonActionPerformed(evt);
            }
        });
        unscannableItemsButtons.add(foodCourtButton);

        bulkButton.setBackground(new java.awt.Color(255, 204, 0));
        bulkButton.setText("BULK");
        bulkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bulkButtonActionPerformed(evt);
            }
        });
        unscannableItemsButtons.add(bulkButton);

        unscannableItemsPanels.setLayout(new java.awt.CardLayout());

        producePanel.setLayout(new java.awt.GridLayout(5, 5, 15, 15));

        cornButton.setText("Corn");
        cornButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cornButtonActionPerformed(evt);
            }
        });
        producePanel.add(cornButton);

        potatoButton.setText("Potato");
        potatoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potatoButtonActionPerformed(evt);
            }
        });
        producePanel.add(potatoButton);

        garlicButton.setText("Garlic");
        producePanel.add(garlicButton);

        broccoliButton.setText("Broccoli");
        broccoliButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                broccoliButtonActionPerformed(evt);
            }
        });
        producePanel.add(broccoliButton);

        carrotButton.setText("Carrot");
        producePanel.add(carrotButton);

        cucumberButton.setText("Cucumber");
        producePanel.add(cucumberButton);

        onionButton.setText("Onion");
        producePanel.add(onionButton);

        greenBeanButton.setText("Green Bean");
        producePanel.add(greenBeanButton);

        lettuceButton.setText("Lettuce");
        producePanel.add(lettuceButton);

        spinachButton.setText("Spinach");
        producePanel.add(spinachButton);

        unscannableItemsPanels.add(producePanel, "card2");

        fruitPanel.setLayout(new java.awt.GridLayout(5, 5, 15, 15));

        appleButton.setText("Apple");
        appleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appleButtonActionPerformed(evt);
            }
        });
        fruitPanel.add(appleButton);

        orangeButton.setText("Orange");
        orangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orangeButtonActionPerformed(evt);
            }
        });
        fruitPanel.add(orangeButton);

        bananaButton.setText("Banana");
        fruitPanel.add(bananaButton);

        grapesButton.setText("Grapes");
        fruitPanel.add(grapesButton);

        strawberriesButton.setText("Strawberries");
        fruitPanel.add(strawberriesButton);

        cherriesButton.setText("Cherries");
        fruitPanel.add(cherriesButton);

        pineappleButton.setText("Pineapple");
        fruitPanel.add(pineappleButton);

        watermelonButton.setText("Watermelon");
        fruitPanel.add(watermelonButton);

        kiwiButton.setText("Kiwi");
        fruitPanel.add(kiwiButton);

        mangoButton.setText("Mango");
        fruitPanel.add(mangoButton);

        unscannableItemsPanels.add(fruitPanel, "card2");

        deliPanel.setLayout(new java.awt.GridLayout(5, 5, 15, 15));

        hamButton.setText("Ham");
        deliPanel.add(hamButton);

        turkeyButton.setText("Turkey");
        deliPanel.add(turkeyButton);

        roastBeefButton.setText("Roast Beef");
        deliPanel.add(roastBeefButton);

        salamiButton.setText("Salami");
        deliPanel.add(salamiButton);

        bolognaButton.setText("Bologna");
        deliPanel.add(bolognaButton);

        cheddarButton.setText("Cheddar");
        deliPanel.add(cheddarButton);

        swissButton.setText("Swiss");
        deliPanel.add(swissButton);

        pepperJackButton.setText("Pepper Jack");
        deliPanel.add(pepperJackButton);

        mozzarellaButton.setText("Mozzarella");
        deliPanel.add(mozzarellaButton);

        goudaButton.setText("Gouda");
        deliPanel.add(goudaButton);

        unscannableItemsPanels.add(deliPanel, "card2");

        bakeryPanel.setLayout(new java.awt.GridLayout(5, 5, 15, 15));

        whiteLoafButton.setText("White Loaf");
        bakeryPanel.add(whiteLoafButton);

        wheatLoafButton.setText("Wheat Loaf");
        bakeryPanel.add(wheatLoafButton);

        ryeLoafButton.setText("Rye Loaf");
        bakeryPanel.add(ryeLoafButton);

        sourdoughLoafButton.setText("Sourdough Loaf");
        bakeryPanel.add(sourdoughLoafButton);

        baguetteButton.setText("Baguette");
        bakeryPanel.add(baguetteButton);

        bagelButton.setText("Bagel");
        bakeryPanel.add(bagelButton);

        rollsButton.setText("Rolls");
        bakeryPanel.add(rollsButton);

        cookiesButton.setText("Cookies");
        bakeryPanel.add(cookiesButton);

        muffinButton.setText("Muffin");
        bakeryPanel.add(muffinButton);

        cakeButton.setText("Cake");
        bakeryPanel.add(cakeButton);

        unscannableItemsPanels.add(bakeryPanel, "card2");

        foodCourtPanel.setLayout(new java.awt.GridLayout(5, 5, 15, 15));

        pizzaSliceButton.setText("Pizza Slice");
        foodCourtPanel.add(pizzaSliceButton);

        wholePizzaButton.setText("Whole Pizza");
        wholePizzaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wholePizzaButtonActionPerformed(evt);
            }
        });
        foodCourtPanel.add(wholePizzaButton);

        hotDogButton.setText("Hot Dog");
        foodCourtPanel.add(hotDogButton);

        sandwichButton.setText("Sandwich");
        foodCourtPanel.add(sandwichButton);

        saladButton.setText("Salad");
        foodCourtPanel.add(saladButton);

        soupButton.setText("Soup");
        foodCourtPanel.add(soupButton);

        iceCreamButton.setText("Ice Cream");
        foodCourtPanel.add(iceCreamButton);

        churrosButton.setText("Churros");
        foodCourtPanel.add(churrosButton);

        smallDrinkButton.setText("Small Drink");
        foodCourtPanel.add(smallDrinkButton);

        largeDrinkButton.setText("Large Drink");
        foodCourtPanel.add(largeDrinkButton);

        unscannableItemsPanels.add(foodCourtPanel, "card2");

        bulkPanel.setLayout(new java.awt.GridLayout(5, 5, 15, 15));

        oatsButton.setText("Oats");
        bulkPanel.add(oatsButton);

        granolaButton.setText("Granola");
        bulkPanel.add(granolaButton);

        peanutsButton.setText("Peanuts");
        bulkPanel.add(peanutsButton);

        almondsButton.setText("Almonds");
        bulkPanel.add(almondsButton);

        cashewsButton.setText("Cashews");
        bulkPanel.add(cashewsButton);

        flourButton.setText("Flour");
        bulkPanel.add(flourButton);

        sugarButton.setText("Sugar");
        bulkPanel.add(sugarButton);

        trailMixButton.setText("Trail Mix");
        bulkPanel.add(trailMixButton);

        driedFruitButton.setText("Dried Fruit");
        bulkPanel.add(driedFruitButton);

        candyButton.setText("Candy");
        bulkPanel.add(candyButton);

        unscannableItemsPanels.add(bulkPanel, "card2");

        jPanelTotal.setLayout(new java.awt.GridLayout(2, 3, 5, 0));

        jLabel4.setText("Sub-Total:");
        jPanelTotal.add(jLabel4);

        jLabel5.setText("Tax:");
        jPanelTotal.add(jLabel5);

        jLabel6.setText("TOTAL:");
        jPanelTotal.add(jLabel6);

        subTotalLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        subTotalLabel.setForeground(new java.awt.Color(0, 153, 51));
        jPanelTotal.add(subTotalLabel);

        taxLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        taxLabel.setForeground(new java.awt.Color(0, 153, 0));
        jPanelTotal.add(taxLabel);

        totalLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        totalLabel.setForeground(new java.awt.Color(204, 51, 0));
        jPanelTotal.add(totalLabel);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        lowerMenuPanel.setLayout(new java.awt.GridLayout(1, 0));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bar.png"))); // NOI18N
        jButton8.setText("Scan");
        lowerMenuPanel.add(jButton8);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/discount.png"))); // NOI18N
        lowerMenuPanel.add(jButton9);

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/void.png"))); // NOI18N
        jButton19.setText("Void");
        lowerMenuPanel.add(jButton19);

        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pay.png"))); // NOI18N
        jButton20.setText("Pay");
        lowerMenuPanel.add(jButton20);

        javax.swing.GroupLayout registerPanelLayout = new javax.swing.GroupLayout(registerPanel);
        registerPanel.setLayout(registerPanelLayout);
        registerPanelLayout.setHorizontalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(unscannableItemsPanels, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lowerMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addComponent(unscannableItemsButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        registerPanelLayout.setVerticalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
                        .addComponent(unscannableItemsButtons, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(60, Short.MAX_VALUE))
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(unscannableItemsPanels, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
                                .addComponent(lowerMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))))))
        );

        mainPanels.add(registerPanel, "card2");

        menuPanel.setLayout(new java.awt.GridLayout(1, 0, 5, 5));

        inventoryButton.setText("Inventory");
        inventoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryButtonActionPerformed(evt);
            }
        });
        menuPanel.add(inventoryButton);

        addItemButton.setText("Add New Product");
        addItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemButtonActionPerformed(evt);
            }
        });
        menuPanel.add(addItemButton);

        registerEmployeeButton.setText("Register Employee");
        registerEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerEmployeeButtonActionPerformed(evt);
            }
        });
        menuPanel.add(registerEmployeeButton);

        jButton7.setText("Set Discount Rate");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        menuPanel.add(jButton7);

        jLayeredPane3.setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        jButton3.setBackground(new java.awt.Color(255, 153, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Look up Item");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);

        jButton5.setBackground(new java.awt.Color(255, 153, 0));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Reorder");
        jPanel1.add(jButton5);

        jButton6.setBackground(new java.awt.Color(255, 153, 0));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Fix quantity");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);

        jButton10.setBackground(new java.awt.Color(255, 153, 0));
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Print Inventory");
        jPanel1.add(jButton10);

        jLayeredPaneInventory.setLayout(new java.awt.CardLayout());

        jPanel2.setLayout(new java.awt.GridLayout(2, 2));

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setText("Product Name");
        jPanel2.add(jButton1);
        jPanel2.add(jTextField3);

        jButton11.setBackground(new java.awt.Color(255, 153, 0));
        jButton11.setText("Product SKU");
        jPanel2.add(jButton11);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout lookItemPanelLayout = new javax.swing.GroupLayout(lookItemPanel);
        lookItemPanel.setLayout(lookItemPanelLayout);
        lookItemPanelLayout.setHorizontalGroup(
            lookItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lookItemPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        lookItemPanelLayout.setVerticalGroup(
            lookItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lookItemPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(lookItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jLayeredPaneInventory.add(lookItemPanel, "card2");

        jPanel3.setLayout(new java.awt.GridLayout(3, 2, 0, 15));

        jButton12.setBackground(new java.awt.Color(255, 153, 0));
        jButton12.setText("Product Name");
        jPanel3.add(jButton12);
        jPanel3.add(jTextField4);

        jButton13.setBackground(new java.awt.Color(255, 153, 0));
        jButton13.setText("Product SKU");
        jPanel3.add(jButton13);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField5);

        jButton14.setBackground(new java.awt.Color(255, 153, 0));
        jButton14.setText("New Quantity");
        jPanel3.add(jButton14);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField6);

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout fixQuantityPanelLayout = new javax.swing.GroupLayout(fixQuantityPanel);
        fixQuantityPanel.setLayout(fixQuantityPanelLayout);
        fixQuantityPanelLayout.setHorizontalGroup(
            fixQuantityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fixQuantityPanelLayout.createSequentialGroup()
                .addGroup(fixQuantityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fixQuantityPanelLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fixQuantityPanelLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        fixQuantityPanelLayout.setVerticalGroup(
            fixQuantityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fixQuantityPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPaneInventory.add(fixQuantityPanel, "card3");

        javax.swing.GroupLayout inventoryPanelLayout = new javax.swing.GroupLayout(inventoryPanel);
        inventoryPanel.setLayout(inventoryPanelLayout);
        inventoryPanelLayout.setHorizontalGroup(
            inventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventoryPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(inventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLayeredPaneInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        inventoryPanelLayout.setVerticalGroup(
            inventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventoryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLayeredPaneInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jLayeredPane3.add(inventoryPanel, "card2");

        jPanel4.setLayout(new java.awt.GridLayout(5, 2, 0, 15));

        jLabel2.setText("Product Name");
        jPanel4.add(jLabel2);

        jTextField2.setText("jTextField2");
        jPanel4.add(jTextField2);

        jLabel10.setText("Category");
        jPanel4.add(jLabel10);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Produce", "Fruit", "Deli", "Bakery", "Food Court", "Bulk" }));
        jPanel4.add(jComboBox1);

        jLabel7.setText("Quantity");
        jPanel4.add(jLabel7);

        jTextField9.setText("jTextField2");
        jPanel4.add(jTextField9);

        jLabel3.setText("SKU");
        jPanel4.add(jLabel3);

        jTextField8.setText("jTextField2");
        jPanel4.add(jTextField8);

        jLabel9.setText("Price");
        jPanel4.add(jLabel9);

        jTextField7.setText("jTextField2");
        jPanel4.add(jTextField7);

        jButton15.setText("Add New Product");

        javax.swing.GroupLayout addNewProductPanelLayout = new javax.swing.GroupLayout(addNewProductPanel);
        addNewProductPanel.setLayout(addNewProductPanelLayout);
        addNewProductPanelLayout.setHorizontalGroup(
            addNewProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNewProductPanelLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addComponent(jButton15)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        addNewProductPanelLayout.setVerticalGroup(
            addNewProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNewProductPanelLayout.createSequentialGroup()
                .addGroup(addNewProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addNewProductPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addNewProductPanelLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jButton15)))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jLayeredPane3.add(addNewProductPanel, "card3");

        labelPanel.setLayout(new java.awt.GridLayout(0, 2));

        firstLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        firstLabel.setText("First Name");
        labelPanel.add(firstLabel);
        labelPanel.add(firstNameTextField);

        last.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        last.setText("Last Name");
        labelPanel.add(last);

        lastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextFieldActionPerformed(evt);
            }
        });
        labelPanel.add(lastNameTextField);

        pass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pass.setText("PassCode");
        labelPanel.add(pass);

        passcodeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passcodeTextFieldActionPerformed(evt);
            }
        });
        labelPanel.add(passcodeTextField);

        SSN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SSN.setText("S.S.N.");
        labelPanel.add(SSN);
        labelPanel.add(ssnTextField);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Date of Birth");
        labelPanel.add(jLabel8);

        birthTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthTextFieldActionPerformed(evt);
            }
        });
        labelPanel.add(birthTextField);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 153, 0));
        jButton4.setText("Register");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registerEmployeePanelLayout = new javax.swing.GroupLayout(registerEmployeePanel);
        registerEmployeePanel.setLayout(registerEmployeePanelLayout);
        registerEmployeePanelLayout.setHorizontalGroup(
            registerEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerEmployeePanelLayout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(labelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
        );
        registerEmployeePanelLayout.setVerticalGroup(
            registerEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerEmployeePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26))
            .addGroup(registerEmployeePanelLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        jLayeredPane3.add(registerEmployeePanel, "card2");

        javax.swing.GroupLayout discountPanelLayout = new javax.swing.GroupLayout(discountPanel);
        discountPanel.setLayout(discountPanelLayout);
        discountPanelLayout.setHorizontalGroup(
            discountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 908, Short.MAX_VALUE)
        );
        discountPanelLayout.setVerticalGroup(
            discountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 366, Short.MAX_VALUE)
        );

        jLayeredPane3.add(discountPanel, "card2");

        javax.swing.GroupLayout managementPanelLayout = new javax.swing.GroupLayout(managementPanel);
        managementPanel.setLayout(managementPanelLayout);
        managementPanelLayout.setHorizontalGroup(
            managementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managementPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(managementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLayeredPane3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        managementPanelLayout.setVerticalGroup(
            managementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managementPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        mainPanels.add(managementPanel, "card3");

        loginArea.setLayout(new java.awt.GridLayout(2, 3, 3, 3));

        usernameLabel.setText("Username");
        loginArea.add(usernameLabel);

        passwordLabel.setText("Password");
        loginArea.add(passwordLabel);
        loginArea.add(fillerLabel);
        loginArea.add(usernameField);
        loginArea.add(passwordField);

        submitButton.setText("Log In");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        loginArea.add(submitButton);

        loginMessageLabel.setFont(new java.awt.Font(".SF NS Text", 0, 24)); // NOI18N
        loginMessageLabel.setText("Not logged in.");

        logOutButton.setText("Log Out");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(loginPanelLayout.createSequentialGroup()
                    .addComponent(loginArea, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(loginMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(203, Short.MAX_VALUE))
            .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(loginPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(loginArea, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(413, Short.MAX_VALUE)))
        );

        mainPanels.add(loginPanel, "card3");

        FrameMenuPanel.setLayout(new java.awt.GridLayout(1, 0));

        registerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        registerButton.setText("REGISTER");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        FrameMenuPanel.add(registerButton);

        logInButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login.png"))); // NOI18N
        logInButton.setText("LOG IN");
        logInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInButtonActionPerformed(evt);
            }
        });
        FrameMenuPanel.add(logInButton);

        managementButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/settings.png"))); // NOI18N
        managementButton.setText("MANAGEMENT");
        managementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managementButtonActionPerformed(evt);
            }
        });
        FrameMenuPanel.add(managementButton);

        userInfoLabel1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        userInfoLabel1.setForeground(new java.awt.Color(0, 0, 204));
        userInfoLabel1.setText("Logged Out");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mainPanels, javax.swing.GroupLayout.PREFERRED_SIZE, 909, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(FrameMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(userInfoLabel1)
                                .addGap(49, 49, 49)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(userInfoLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(FrameMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addComponent(mainPanels, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoActionPerformed

    private void fruitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fruitButtonActionPerformed
        switchPanels(unscannableItemsPanels, fruitPanel);
    }//GEN-LAST:event_fruitButtonActionPerformed

    private void appleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appleButtonActionPerformed
        jTextArea1.append(apple.toString());
        updateTotal(apple.getPrice());
    }//GEN-LAST:event_appleButtonActionPerformed

    private void cornButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cornButtonActionPerformed
        jTextArea1.append(corn.toString());
        updateTotal(corn.getPrice());
        //subTotalLabel.setText(String.format("%.2f", potato.getPrice()));
    }//GEN-LAST:event_cornButtonActionPerformed

    private void produceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produceButtonActionPerformed
        switchPanels(unscannableItemsPanels, producePanel);
    }//GEN-LAST:event_produceButtonActionPerformed

    private void deliButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliButtonActionPerformed
        switchPanels(unscannableItemsPanels, deliPanel);
    }//GEN-LAST:event_deliButtonActionPerformed

    private void orangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orangeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orangeButtonActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        // TODO add your handling code here:
        switchPanels(mainPanels, registerPanel);
    }//GEN-LAST:event_registerButtonActionPerformed

    private void managementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managementButtonActionPerformed
        // TODO add your handling code here:
        switchPanels(mainPanels, managementPanel);
    }//GEN-LAST:event_managementButtonActionPerformed

    private void potatoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potatoButtonActionPerformed
        // TODO add your handling code here:
        jTextArea1.append(potato.toString());
        updateTotal(potato.getPrice());
    }//GEN-LAST:event_potatoButtonActionPerformed

    private void broccoliButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_broccoliButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_broccoliButtonActionPerformed

    private void wholePizzaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wholePizzaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wholePizzaButtonActionPerformed

    private void bakeryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bakeryButtonActionPerformed
        switchPanels(unscannableItemsPanels, bakeryPanel);
    }//GEN-LAST:event_bakeryButtonActionPerformed

    private void foodCourtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodCourtButtonActionPerformed
        switchPanels(unscannableItemsPanels, foodCourtPanel);
    }//GEN-LAST:event_foodCourtButtonActionPerformed

    private void bulkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bulkButtonActionPerformed
        switchPanels(unscannableItemsPanels, bulkPanel);
    }//GEN-LAST:event_bulkButtonActionPerformed

    private void logInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInButtonActionPerformed
        switchPanels(mainPanels, loginPanel);
    }//GEN-LAST:event_logInButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        if (passwordField.getPassword().length > 0){ loginMessageLabel.setText("Logged in as: " + usernameField.getText());
        userInfoLabel1.setText("Cashier: " + usernameField.getText());
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        loginMessageLabel.setText("Successfully logged out.");
        userInfoLabel1.setText("Logged Out");
    }//GEN-LAST:event_logOutButtonActionPerformed

    private void lastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextFieldActionPerformed

    private void passcodeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passcodeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passcodeTextFieldActionPerformed

    private void birthTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthTextFieldActionPerformed

    private void inventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryButtonActionPerformed
        // TODO add your handling code here:
        switchPanels(jLayeredPane3, inventoryPanel);
    }//GEN-LAST:event_inventoryButtonActionPerformed

    private void addItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemButtonActionPerformed
        // TODO add your handling code here:
        switchPanels(jLayeredPane3, addNewProductPanel);
    }//GEN-LAST:event_addItemButtonActionPerformed

    private void registerEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerEmployeeButtonActionPerformed
        // TODO add your handling code here:
        switchPanels(jLayeredPane3, registerEmployeePanel);
    }//GEN-LAST:event_registerEmployeeButtonActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        switchPanels(jLayeredPane3, discountPanel);
    }//GEN-LAST:event_jButton7ActionPerformed
     
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        employeeList[employeeNum] = new NewEmployee(firstNameTextField.getText(),lastNameTextField.getText(),
        passcodeTextField.getText(), ssnTextField.getText());
        employeeNum++;
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        switchPanels(jLayeredPaneInventory, lookItemPanel);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        switchPanels(jLayeredPaneInventory, fixQuantityPanel);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed
    
    NewEmployee employeeList[] = new NewEmployee[99];
    int employeeNum= 0;
    
    double subtotal=0;
    double tax=0;
    double total=0;
    Item potato = new Item("Potato","0001", 0.99,25);
    Item lettuce = new Item("Lettuce", "0002", 1.05, 39);
    Item apple = new Item("Apple","0003", 0.50, 100);
    Item corn = new Item("Corn","0004", 0.50, 100);
    //Item i = new Item("i","0005", 0.50, 100);
    //Item i = new Item("i","0006", 0.50, 100);
    //Item i = new Item("i","0007", 0.50, 100); 
    //Item i = new Item("i","0008", 0.50, 100);
    //Item i = new Item("i","0009", 0.50, 100);
    /**
     * @param args the command line arguments
     */
    
    
    public void switchPanels(JLayeredPane pane, JPanel panel)
    {
        pane.removeAll();
        pane.add(panel);
        pane.repaint();
        pane.revalidate();
        
    }
    public void updateTotal(double price)
    {
        subtotal = subtotal + price;
        tax = subtotal *0.0925;
        total = subtotal + tax;
        subTotalLabel.setText(String.format("%.2f", subtotal));
        taxLabel.setText(String.format("%.2f",tax));
        totalLabel.setText(String.format("%.2f",total));
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grocery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grocery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grocery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grocery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grocery().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FrameMenuPanel;
    private javax.swing.JLabel SSN;
    private javax.swing.JButton addItemButton;
    private javax.swing.JPanel addNewProductPanel;
    private javax.swing.JButton almondsButton;
    private javax.swing.JButton appleButton;
    private javax.swing.JButton bagelButton;
    private javax.swing.JButton baguetteButton;
    private javax.swing.JButton bakeryButton;
    private javax.swing.JPanel bakeryPanel;
    private javax.swing.JButton bananaButton;
    private javax.swing.JTextField birthTextField;
    private javax.swing.JButton bolognaButton;
    private javax.swing.JButton broccoliButton;
    private javax.swing.JButton bulkButton;
    private javax.swing.JPanel bulkPanel;
    private javax.swing.JButton cakeButton;
    private javax.swing.JButton candyButton;
    private javax.swing.JButton carrotButton;
    private javax.swing.JButton cashewsButton;
    private javax.swing.JButton cheddarButton;
    private javax.swing.JButton cherriesButton;
    private javax.swing.JButton churrosButton;
    private javax.swing.JButton cookiesButton;
    private javax.swing.JButton cornButton;
    private javax.swing.JButton cucumberButton;
    private javax.swing.JButton deliButton;
    private javax.swing.JPanel deliPanel;
    private javax.swing.JPanel discountPanel;
    private javax.swing.JButton driedFruitButton;
    private javax.swing.JLabel fillerLabel;
    private javax.swing.JLabel firstLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JPanel fixQuantityPanel;
    private javax.swing.JButton flourButton;
    private javax.swing.JButton foodCourtButton;
    private javax.swing.JPanel foodCourtPanel;
    private javax.swing.JButton fruitButton;
    private javax.swing.JPanel fruitPanel;
    private javax.swing.JButton garlicButton;
    private javax.swing.JButton goudaButton;
    private javax.swing.JButton granolaButton;
    private javax.swing.JButton grapesButton;
    private javax.swing.JButton greenBeanButton;
    private javax.swing.JButton hamButton;
    private javax.swing.JButton hotDogButton;
    private javax.swing.JButton iceCreamButton;
    private javax.swing.JButton inventoryButton;
    private javax.swing.JPanel inventoryPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPaneInventory;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelTotal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton kiwiButton;
    private javax.swing.JPanel labelPanel;
    private javax.swing.JButton largeDrinkButton;
    private javax.swing.JLabel last;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JButton lettuceButton;
    private javax.swing.JButton logInButton;
    private javax.swing.JButton logOutButton;
    private javax.swing.JPanel loginArea;
    private javax.swing.JLabel loginMessageLabel;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JButton logo;
    private javax.swing.JPanel lookItemPanel;
    private javax.swing.JPanel lowerMenuPanel;
    private javax.swing.JLayeredPane mainPanels;
    private javax.swing.JButton managementButton;
    private javax.swing.JPanel managementPanel;
    private javax.swing.JButton mangoButton;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JButton mozzarellaButton;
    private javax.swing.JButton muffinButton;
    private javax.swing.JButton oatsButton;
    private javax.swing.JButton onionButton;
    private javax.swing.JButton orangeButton;
    private javax.swing.JLabel pass;
    private javax.swing.JTextField passcodeTextField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton peanutsButton;
    private javax.swing.JButton pepperJackButton;
    private javax.swing.JButton pineappleButton;
    private javax.swing.JButton pizzaSliceButton;
    private javax.swing.JButton potatoButton;
    private javax.swing.JButton produceButton;
    private javax.swing.JPanel producePanel;
    private javax.swing.JButton registerButton;
    private javax.swing.JButton registerEmployeeButton;
    private javax.swing.JPanel registerEmployeePanel;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JButton roastBeefButton;
    private javax.swing.JButton rollsButton;
    private javax.swing.JButton ryeLoafButton;
    private javax.swing.JButton saladButton;
    private javax.swing.JButton salamiButton;
    private javax.swing.JButton sandwichButton;
    private javax.swing.JButton smallDrinkButton;
    private javax.swing.JButton soupButton;
    private javax.swing.JButton sourdoughLoafButton;
    private javax.swing.JButton spinachButton;
    private javax.swing.JTextField ssnTextField;
    private javax.swing.JButton strawberriesButton;
    private javax.swing.JLabel subTotalLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JButton sugarButton;
    private javax.swing.JButton swissButton;
    private javax.swing.JLabel taxLabel;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JButton trailMixButton;
    private javax.swing.JButton turkeyButton;
    private javax.swing.JPanel unscannableItemsButtons;
    private javax.swing.JLabel unscannableItemsLabel;
    private javax.swing.JLayeredPane unscannableItemsPanels;
    private javax.swing.JLabel userInfoLabel1;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JButton watermelonButton;
    private javax.swing.JButton wheatLoafButton;
    private javax.swing.JButton whiteLoafButton;
    private javax.swing.JButton wholePizzaButton;
    // End of variables declaration//GEN-END:variables
}
