/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pos;

import javax.swing.JPanel;

/**
 *
 * @author Edwin
 */
public class Grocery extends javax.swing.JFrame {

    /**
     * Creates new form Grocery
     */
    public Grocery() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        registerPanel = new javax.swing.JPanel();
        jPanelCategories = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonProduce = new javax.swing.JButton();
        jButtonFruit = new javax.swing.JButton();
        jButtonFrozenFood = new javax.swing.JButton();
        jButtonBakery = new javax.swing.JButton();
        jButtonDrinks = new javax.swing.JButton();
        jButtonCannedFood = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        fruitPanel = new javax.swing.JPanel();
        appleButton = new javax.swing.JButton();
        pineappleButton = new javax.swing.JButton();
        strawberriesButton = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        frozenFoodPanel = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        producePanel = new javax.swing.JPanel();
        potatoButton = new javax.swing.JButton();
        lettuceButton = new javax.swing.JButton();
        tomatoButton = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanelTotal = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        subTotalLabel = new javax.swing.JLabel();
        taxLabel = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lowerMenuPanel = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        managementPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        FrameMenuPanel = new javax.swing.JPanel();
        registerButton = new javax.swing.JButton();
        logInButton = new javax.swing.JButton();
        managementButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        logo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoActionPerformed(evt);
            }
        });

        jLayeredPane2.setLayout(new java.awt.CardLayout());

        jPanelCategories.setLayout(new java.awt.GridLayout(0, 1, 3, 3));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("CATEGORIES");
        jPanelCategories.add(jLabel1);

        jButtonProduce.setBackground(new java.awt.Color(255, 204, 0));
        jButtonProduce.setForeground(new java.awt.Color(255, 255, 255));
        jButtonProduce.setText("PRODUCE");
        jButtonProduce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProduceActionPerformed(evt);
            }
        });
        jPanelCategories.add(jButtonProduce);

        jButtonFruit.setBackground(new java.awt.Color(255, 204, 0));
        jButtonFruit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFruit.setText("FRUIT");
        jButtonFruit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFruitActionPerformed(evt);
            }
        });
        jPanelCategories.add(jButtonFruit);

        jButtonFrozenFood.setBackground(new java.awt.Color(255, 204, 0));
        jButtonFrozenFood.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFrozenFood.setText("FROZEN FOOD");
        jButtonFrozenFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFrozenFoodActionPerformed(evt);
            }
        });
        jPanelCategories.add(jButtonFrozenFood);

        jButtonBakery.setBackground(new java.awt.Color(255, 204, 0));
        jButtonBakery.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBakery.setText("BAKERY");
        jPanelCategories.add(jButtonBakery);

        jButtonDrinks.setBackground(new java.awt.Color(255, 204, 0));
        jButtonDrinks.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDrinks.setText("DRINKS");
        jPanelCategories.add(jButtonDrinks);

        jButtonCannedFood.setBackground(new java.awt.Color(255, 204, 0));
        jButtonCannedFood.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCannedFood.setText("CANNED FOOD");
        jPanelCategories.add(jButtonCannedFood);

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        fruitPanel.setLayout(new java.awt.GridLayout(5, 5, 15, 15));

        appleButton.setText("Apple");
        appleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appleButtonActionPerformed(evt);
            }
        });
        fruitPanel.add(appleButton);

        pineappleButton.setText("Pineapple");
        pineappleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pineappleButtonActionPerformed(evt);
            }
        });
        fruitPanel.add(pineappleButton);

        strawberriesButton.setText("Strawberries");
        fruitPanel.add(strawberriesButton);

        jButton10.setText("jButton1");
        fruitPanel.add(jButton10);

        jButton11.setText("jButton1");
        fruitPanel.add(jButton11);

        jButton12.setText("jButton1");
        fruitPanel.add(jButton12);

        jLayeredPane1.add(fruitPanel, "card2");

        frozenFoodPanel.setLayout(new java.awt.GridLayout(5, 5, 15, 15));

        jButton13.setText("Fozen Pizza");
        frozenFoodPanel.add(jButton13);

        jButton14.setText("jButton1");
        frozenFoodPanel.add(jButton14);

        jButton15.setText("jButton1");
        frozenFoodPanel.add(jButton15);

        jButton16.setText("jButton1");
        frozenFoodPanel.add(jButton16);

        jButton17.setText("jButton1");
        frozenFoodPanel.add(jButton17);

        jButton18.setText("jButton1");
        frozenFoodPanel.add(jButton18);

        jLayeredPane1.add(frozenFoodPanel, "card2");

        producePanel.setLayout(new java.awt.GridLayout(5, 5, 15, 15));

        potatoButton.setText("Potato");
        potatoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potatoButtonActionPerformed(evt);
            }
        });
        producePanel.add(potatoButton);

        lettuceButton.setText("Lettuce");
        lettuceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lettuceButtonActionPerformed(evt);
            }
        });
        producePanel.add(lettuceButton);

        tomatoButton.setText("Tomato");
        producePanel.add(tomatoButton);

        jButton4.setText("jButton1");
        producePanel.add(jButton4);

        jButton5.setText("jButton1");
        producePanel.add(jButton5);

        jButton6.setText("jButton1");
        producePanel.add(jButton6);

        jLayeredPane1.add(producePanel, "card2");

        jPanelTotal.setLayout(new java.awt.GridLayout(2, 3, 5, 5));

        jLabel4.setText("Sub-Total:");
        jPanelTotal.add(jLabel4);

        jLabel5.setText("Tax:");
        jPanelTotal.add(jLabel5);

        jLabel6.setText("TOTAL:");
        jPanelTotal.add(jLabel6);

        subTotalLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        subTotalLabel.setForeground(new java.awt.Color(0, 153, 51));
        jPanelTotal.add(subTotalLabel);

        taxLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        taxLabel.setForeground(new java.awt.Color(0, 153, 0));
        jPanelTotal.add(taxLabel);

        totalLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totalLabel.setForeground(new java.awt.Color(0, 153, 0));
        jPanelTotal.add(totalLabel);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        lowerMenuPanel.setLayout(new java.awt.GridLayout());

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bar.png"))); // NOI18N
        jButton8.setText("Scan");
        lowerMenuPanel.add(jButton8);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/discount.png"))); // NOI18N
        jButton9.setText("Discount");
        lowerMenuPanel.add(jButton9);

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/void.png"))); // NOI18N
        jButton19.setText("Item Void");
        lowerMenuPanel.add(jButton19);

        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pay.png"))); // NOI18N
        jButton20.setText("Pay");
        lowerMenuPanel.add(jButton20);

        javax.swing.GroupLayout registerPanelLayout = new javax.swing.GroupLayout(registerPanel);
        registerPanel.setLayout(registerPanelLayout);
        registerPanelLayout.setHorizontalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lowerMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)))
                .addComponent(jPanelCategories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        registerPanelLayout.setVerticalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
                        .addComponent(jPanelCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
                                .addComponent(lowerMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30))))))
        );

        jLayeredPane2.add(registerPanel, "card2");

        menuPanel.setLayout(new java.awt.GridLayout(1, 0, 5, 5));

        jButton1.setText("Inventory");
        menuPanel.add(jButton1);

        jButton2.setText("Add New Item");
        menuPanel.add(jButton2);

        jButton3.setText("Register Employee");
        menuPanel.add(jButton3);

        jButton7.setText("Set Discount Rate");
        menuPanel.add(jButton7);

        jLayeredPane3.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLayeredPane3.add(jPanel1, "card2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLayeredPane3.add(jPanel2, "card3");

        javax.swing.GroupLayout managementPanelLayout = new javax.swing.GroupLayout(managementPanel);
        managementPanel.setLayout(managementPanelLayout);
        managementPanelLayout.setHorizontalGroup(
            managementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managementPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(managementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        managementPanelLayout.setVerticalGroup(
            managementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managementPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(306, Short.MAX_VALUE))
        );

        jLayeredPane2.add(managementPanel, "card3");

        FrameMenuPanel.setLayout(new java.awt.GridLayout());

        registerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        registerButton.setText("REGISTER");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        FrameMenuPanel.add(registerButton);

        logInButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login.png"))); // NOI18N
        logInButton.setText("LOG IN");
        FrameMenuPanel.add(logInButton);

        managementButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/settings.png"))); // NOI18N
        managementButton.setText("MANAGEMENT");
        managementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managementButtonActionPerformed(evt);
            }
        });
        FrameMenuPanel.add(managementButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 909, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(FrameMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FrameMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoActionPerformed

    private void jButtonFruitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFruitActionPerformed
        // TODO add your handling code here:
        switchPanels(fruitPanel);
    }//GEN-LAST:event_jButtonFruitActionPerformed

    private void appleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appleButtonActionPerformed
        // TODO add your handling code here:
        jTextArea1.append(apple.toString());
        updateTotal(apple.getPrice());
    }//GEN-LAST:event_appleButtonActionPerformed

    private void potatoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potatoButtonActionPerformed
        // TODO add your handling code here:
        jTextArea1.append(potato.toString());
        updateTotal(potato.getPrice());
        //subTotalLabel.setText(String.format("%.2f", potato.getPrice()));
    }//GEN-LAST:event_potatoButtonActionPerformed

    private void jButtonProduceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProduceActionPerformed
        switchPanels(producePanel);
    }//GEN-LAST:event_jButtonProduceActionPerformed

    private void jButtonFrozenFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFrozenFoodActionPerformed
        switchPanels(frozenFoodPanel);
    }//GEN-LAST:event_jButtonFrozenFoodActionPerformed

    private void pineappleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pineappleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pineappleButtonActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        // TODO add your handling code here:
        switchPanels2(registerPanel);
    }//GEN-LAST:event_registerButtonActionPerformed

    private void managementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managementButtonActionPerformed
        // TODO add your handling code here:
        switchPanels2(managementPanel);
    }//GEN-LAST:event_managementButtonActionPerformed

    private void lettuceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lettuceButtonActionPerformed
        // TODO add your handling code here:
        jTextArea1.append(lettuce.toString());
        updateTotal(lettuce.getPrice());
    }//GEN-LAST:event_lettuceButtonActionPerformed
    
    double subtotal=0;
    double tax=0;
    double total=0;
    Item potato = new Item("Potato","0001", 0.99,25);
    Item lettuce = new Item("Lettuce", "0002", 1.05, 39);
    Item apple = new Item("Apple","003", 0.50, 100);
    /**
     * @param args the command line arguments
     */
    public void switchPanels(JPanel panel)
    {
        jLayeredPane1.removeAll();
        jLayeredPane1.add(panel);
        jLayeredPane1.repaint();
        jLayeredPane1.revalidate();
    }
    public void switchPanels2(JPanel panel)
    {
        jLayeredPane2.removeAll();
        jLayeredPane2.add(panel);
        jLayeredPane2.repaint();
        jLayeredPane2.revalidate();
    }
    public void updateTotal(double price)
    {
        subtotal = subtotal + price;
        tax = subtotal *0.0925;
        total = subtotal + tax;
        subTotalLabel.setText(String.format("%.2f", subtotal));
        taxLabel.setText(String.format("%.2f",tax));
        totalLabel.setText(String.format("%.2f",total));
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grocery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grocery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grocery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grocery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grocery().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FrameMenuPanel;
    private javax.swing.JButton appleButton;
    private javax.swing.JPanel frozenFoodPanel;
    private javax.swing.JPanel fruitPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonBakery;
    private javax.swing.JButton jButtonCannedFood;
    private javax.swing.JButton jButtonDrinks;
    private javax.swing.JButton jButtonFrozenFood;
    private javax.swing.JButton jButtonFruit;
    private javax.swing.JButton jButtonProduce;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCategories;
    private javax.swing.JPanel jPanelTotal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton lettuceButton;
    private javax.swing.JButton logInButton;
    private javax.swing.JButton logo;
    private javax.swing.JPanel lowerMenuPanel;
    private javax.swing.JButton managementButton;
    private javax.swing.JPanel managementPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JButton pineappleButton;
    private javax.swing.JButton potatoButton;
    private javax.swing.JPanel producePanel;
    private javax.swing.JButton registerButton;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JButton strawberriesButton;
    private javax.swing.JLabel subTotalLabel;
    private javax.swing.JLabel taxLabel;
    private javax.swing.JButton tomatoButton;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
