/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pos;

import javax.swing.JPanel;

/**
 *
 * @author Edwin
 */
public class Grocery extends javax.swing.JFrame {

    /**
     * Creates new form Grocery
     */
    public Grocery() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JButton();
        mainPanels = new javax.swing.JLayeredPane();
        registerPanel = new javax.swing.JPanel();
        unscannableItemsButtons = new javax.swing.JPanel();
        unscannableItemsLabel = new javax.swing.JLabel();
        produceButton = new javax.swing.JButton();
        fruitButton = new javax.swing.JButton();
        deliButton = new javax.swing.JButton();
        bakeryButton = new javax.swing.JButton();
        foodCourtButton = new javax.swing.JButton();
        bulkButton = new javax.swing.JButton();
        unscannableItemsPanels = new javax.swing.JLayeredPane();
        producePanel = new javax.swing.JPanel();
        cornButton = new javax.swing.JButton();
        potatoButton = new javax.swing.JButton();
        garlicButton = new javax.swing.JButton();
        broccoliButton = new javax.swing.JButton();
        carrotButton = new javax.swing.JButton();
        cucumberButton = new javax.swing.JButton();
        onionButton = new javax.swing.JButton();
        greenBeanButton = new javax.swing.JButton();
        lettuceButton = new javax.swing.JButton();
        spinachButton = new javax.swing.JButton();
        fruitPanel = new javax.swing.JPanel();
        appleButton = new javax.swing.JButton();
        orangeButton = new javax.swing.JButton();
        bananaButton = new javax.swing.JButton();
        grapesButton = new javax.swing.JButton();
        strawberriesButton = new javax.swing.JButton();
        cherriesButton = new javax.swing.JButton();
        pineappleButton = new javax.swing.JButton();
        watermelonButton = new javax.swing.JButton();
        kiwiButton = new javax.swing.JButton();
        mangoButton = new javax.swing.JButton();
        deliPanel = new javax.swing.JPanel();
        hamButton = new javax.swing.JButton();
        turkeyButton = new javax.swing.JButton();
        roastBeefButton = new javax.swing.JButton();
        salamiButton = new javax.swing.JButton();
        bolognaButton = new javax.swing.JButton();
        cheddarButton = new javax.swing.JButton();
        swissButton = new javax.swing.JButton();
        pepperJackButton = new javax.swing.JButton();
        mozzarellaButton = new javax.swing.JButton();
        goudaButton = new javax.swing.JButton();
        bakeryPanel = new javax.swing.JPanel();
        whiteLoafButton = new javax.swing.JButton();
        wheatLoafButton = new javax.swing.JButton();
        ryeLoafButton = new javax.swing.JButton();
        sourdoughLoafButton = new javax.swing.JButton();
        baguetteButton = new javax.swing.JButton();
        bagelButton = new javax.swing.JButton();
        rollsButton = new javax.swing.JButton();
        cookiesButton = new javax.swing.JButton();
        muffinButton = new javax.swing.JButton();
        cakeButton = new javax.swing.JButton();
        foodCourtPanel = new javax.swing.JPanel();
        pizzaSliceButton = new javax.swing.JButton();
        wholePizzaButton = new javax.swing.JButton();
        hotDogButton = new javax.swing.JButton();
        sandwichButton = new javax.swing.JButton();
        saladButton = new javax.swing.JButton();
        soupButton = new javax.swing.JButton();
        iceCreamButton = new javax.swing.JButton();
        churrosButton = new javax.swing.JButton();
        smallDrinkButton = new javax.swing.JButton();
        largeDrinkButton = new javax.swing.JButton();
        bulkPanel = new javax.swing.JPanel();
        oatsButton = new javax.swing.JButton();
        granolaButton = new javax.swing.JButton();
        peanutsButton = new javax.swing.JButton();
        almondsButton = new javax.swing.JButton();
        cashewsButton = new javax.swing.JButton();
        flourButton = new javax.swing.JButton();
        sugarButton = new javax.swing.JButton();
        trailMixButton = new javax.swing.JButton();
        driedFruitButton = new javax.swing.JButton();
        candyButton = new javax.swing.JButton();
        jPanelTotal = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        subTotalLabel = new javax.swing.JLabel();
        taxLabel = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lowerMenuPanel = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        managementPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        loginArea = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        fillerLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        submitButton = new javax.swing.JButton();
        loginMessageLabel = new javax.swing.JLabel();
        logOutButton = new javax.swing.JButton();
        FrameMenuPanel = new javax.swing.JPanel();
        registerButton = new javax.swing.JButton();
        logInButton = new javax.swing.JButton();
        managementButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        logo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoActionPerformed(evt);
            }
        });

        mainPanels.setLayout(new java.awt.CardLayout());

        unscannableItemsButtons.setLayout(new java.awt.GridLayout(0, 1, 3, 3));

        unscannableItemsLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        unscannableItemsLabel.setForeground(new java.awt.Color(0, 0, 102));
        unscannableItemsLabel.setText("CATEGORIES");
        unscannableItemsButtons.add(unscannableItemsLabel);

        produceButton.setBackground(new java.awt.Color(255, 204, 0));
        produceButton.setText("PRODUCE");
        produceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produceButtonActionPerformed(evt);
            }
        });
        unscannableItemsButtons.add(produceButton);

        fruitButton.setBackground(new java.awt.Color(255, 204, 0));
        fruitButton.setText("FRUIT");
        fruitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fruitButtonActionPerformed(evt);
            }
        });
        unscannableItemsButtons.add(fruitButton);

        deliButton.setBackground(new java.awt.Color(255, 204, 0));
        deliButton.setText("DELI");
        deliButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliButtonActionPerformed(evt);
            }
        });
        unscannableItemsButtons.add(deliButton);

        bakeryButton.setBackground(new java.awt.Color(255, 204, 0));
        bakeryButton.setText("BAKERY");
        bakeryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bakeryButtonActionPerformed(evt);
            }
        });
        unscannableItemsButtons.add(bakeryButton);

        foodCourtButton.setBackground(new java.awt.Color(255, 204, 0));
        foodCourtButton.setText("FOOD COURT");
        foodCourtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodCourtButtonActionPerformed(evt);
            }
        });
        unscannableItemsButtons.add(foodCourtButton);

        bulkButton.setBackground(new java.awt.Color(255, 204, 0));
        bulkButton.setText("BULK");
        bulkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bulkButtonActionPerformed(evt);
            }
        });
        unscannableItemsButtons.add(bulkButton);

        unscannableItemsPanels.setLayout(new java.awt.CardLayout());

        producePanel.setLayout(new java.awt.GridLayout(5, 5, 15, 15));

        cornButton.setText("Corn");
        cornButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cornButtonActionPerformed(evt);
            }
        });
        producePanel.add(cornButton);

        potatoButton.setText("Potato");
        potatoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potatoButtonActionPerformed(evt);
            }
        });
        producePanel.add(potatoButton);

        garlicButton.setText("Garlic");
        producePanel.add(garlicButton);

        broccoliButton.setText("Broccoli");
        broccoliButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                broccoliButtonActionPerformed(evt);
            }
        });
        producePanel.add(broccoliButton);

        carrotButton.setText("Carrot");
        producePanel.add(carrotButton);

        cucumberButton.setText("Cucumber");
        producePanel.add(cucumberButton);

        onionButton.setText("Onion");
        producePanel.add(onionButton);

        greenBeanButton.setText("Green Bean");
        producePanel.add(greenBeanButton);

        lettuceButton.setText("Lettuce");
        producePanel.add(lettuceButton);

        spinachButton.setText("Spinach");
        producePanel.add(spinachButton);

        unscannableItemsPanels.add(producePanel, "card2");

        fruitPanel.setLayout(new java.awt.GridLayout(5, 5, 15, 15));

        appleButton.setText("Apple");
        appleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appleButtonActionPerformed(evt);
            }
        });
        fruitPanel.add(appleButton);

        orangeButton.setText("Orange");
        orangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orangeButtonActionPerformed(evt);
            }
        });
        fruitPanel.add(orangeButton);

        bananaButton.setText("Banana");
        fruitPanel.add(bananaButton);

        grapesButton.setText("Grapes");
        fruitPanel.add(grapesButton);

        strawberriesButton.setText("Strawberries");
        fruitPanel.add(strawberriesButton);

        cherriesButton.setText("Cherries");
        fruitPanel.add(cherriesButton);

        pineappleButton.setText("Pineapple");
        fruitPanel.add(pineappleButton);

        watermelonButton.setText("Watermelon");
        fruitPanel.add(watermelonButton);

        kiwiButton.setText("Kiwi");
        fruitPanel.add(kiwiButton);

        mangoButton.setText("Mango");
        fruitPanel.add(mangoButton);

        unscannableItemsPanels.add(fruitPanel, "card2");

        deliPanel.setLayout(new java.awt.GridLayout(5, 5, 15, 15));

        hamButton.setText("Ham");
        deliPanel.add(hamButton);

        turkeyButton.setText("Turkey");
        deliPanel.add(turkeyButton);

        roastBeefButton.setText("Roast Beef");
        deliPanel.add(roastBeefButton);

        salamiButton.setText("Salami");
        deliPanel.add(salamiButton);

        bolognaButton.setText("Bologna");
        deliPanel.add(bolognaButton);

        cheddarButton.setText("Cheddar");
        deliPanel.add(cheddarButton);

        swissButton.setText("Swiss");
        deliPanel.add(swissButton);

        pepperJackButton.setText("Pepper Jack");
        deliPanel.add(pepperJackButton);

        mozzarellaButton.setText("Mozzarella");
        deliPanel.add(mozzarellaButton);

        goudaButton.setText("Gouda");
        deliPanel.add(goudaButton);

        unscannableItemsPanels.add(deliPanel, "card2");

        bakeryPanel.setLayout(new java.awt.GridLayout(5, 5, 15, 15));

        whiteLoafButton.setText("White Loaf");
        bakeryPanel.add(whiteLoafButton);

        wheatLoafButton.setText("Wheat Loaf");
        bakeryPanel.add(wheatLoafButton);

        ryeLoafButton.setText("Rye Loaf");
        bakeryPanel.add(ryeLoafButton);

        sourdoughLoafButton.setText("Sourdough Loaf");
        bakeryPanel.add(sourdoughLoafButton);

        baguetteButton.setText("Baguette");
        bakeryPanel.add(baguetteButton);

        bagelButton.setText("Bagel");
        bakeryPanel.add(bagelButton);

        rollsButton.setText("Rolls");
        bakeryPanel.add(rollsButton);

        cookiesButton.setText("Cookies");
        bakeryPanel.add(cookiesButton);

        muffinButton.setText("Muffin");
        bakeryPanel.add(muffinButton);

        cakeButton.setText("Cake");
        bakeryPanel.add(cakeButton);

        unscannableItemsPanels.add(bakeryPanel, "card2");

        foodCourtPanel.setLayout(new java.awt.GridLayout(5, 5, 15, 15));

        pizzaSliceButton.setText("Pizza Slice");
        foodCourtPanel.add(pizzaSliceButton);

        wholePizzaButton.setText("Whole Pizza");
        wholePizzaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wholePizzaButtonActionPerformed(evt);
            }
        });
        foodCourtPanel.add(wholePizzaButton);

        hotDogButton.setText("Hot Dog");
        foodCourtPanel.add(hotDogButton);

        sandwichButton.setText("Sandwich");
        foodCourtPanel.add(sandwichButton);

        saladButton.setText("Salad");
        foodCourtPanel.add(saladButton);

        soupButton.setText("Soup");
        foodCourtPanel.add(soupButton);

        iceCreamButton.setText("Ice Cream");
        foodCourtPanel.add(iceCreamButton);

        churrosButton.setText("Churros");
        foodCourtPanel.add(churrosButton);

        smallDrinkButton.setText("Small Drink");
        foodCourtPanel.add(smallDrinkButton);

        largeDrinkButton.setText("Large Drink");
        foodCourtPanel.add(largeDrinkButton);

        unscannableItemsPanels.add(foodCourtPanel, "card2");

        bulkPanel.setLayout(new java.awt.GridLayout(5, 5, 15, 15));

        oatsButton.setText("Oats");
        bulkPanel.add(oatsButton);

        granolaButton.setText("Granola");
        bulkPanel.add(granolaButton);

        peanutsButton.setText("Peanuts");
        bulkPanel.add(peanutsButton);

        almondsButton.setText("Almonds");
        bulkPanel.add(almondsButton);

        cashewsButton.setText("Cashews");
        bulkPanel.add(cashewsButton);

        flourButton.setText("Flour");
        bulkPanel.add(flourButton);

        sugarButton.setText("Sugar");
        bulkPanel.add(sugarButton);

        trailMixButton.setText("Trail Mix");
        bulkPanel.add(trailMixButton);

        driedFruitButton.setText("Dried Fruit");
        bulkPanel.add(driedFruitButton);

        candyButton.setText("Candy");
        bulkPanel.add(candyButton);

        unscannableItemsPanels.add(bulkPanel, "card2");

        jPanelTotal.setLayout(new java.awt.GridLayout(2, 3, 5, 5));

        jLabel4.setText("Sub-Total:");
        jPanelTotal.add(jLabel4);

        jLabel5.setText("Tax:");
        jPanelTotal.add(jLabel5);

        jLabel6.setText("TOTAL:");
        jPanelTotal.add(jLabel6);

        subTotalLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        subTotalLabel.setForeground(new java.awt.Color(0, 153, 51));
        jPanelTotal.add(subTotalLabel);

        taxLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        taxLabel.setForeground(new java.awt.Color(0, 153, 0));
        jPanelTotal.add(taxLabel);

        totalLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totalLabel.setForeground(new java.awt.Color(0, 153, 0));
        jPanelTotal.add(totalLabel);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        lowerMenuPanel.setLayout(new java.awt.GridLayout(1, 0));

        jButton8.setText("Scan");
        lowerMenuPanel.add(jButton8);
        lowerMenuPanel.add(jButton9);

        jButton19.setText("Item Void");
        lowerMenuPanel.add(jButton19);

        jButton20.setText("Pay");
        lowerMenuPanel.add(jButton20);

        javax.swing.GroupLayout registerPanelLayout = new javax.swing.GroupLayout(registerPanel);
        registerPanel.setLayout(registerPanelLayout);
        registerPanelLayout.setHorizontalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addComponent(unscannableItemsPanels, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lowerMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(unscannableItemsButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        registerPanelLayout.setVerticalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
                        .addComponent(unscannableItemsButtons, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(unscannableItemsPanels, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
                                .addComponent(lowerMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );

        mainPanels.add(registerPanel, "card2");

        menuPanel.setLayout(new java.awt.GridLayout(1, 0, 5, 5));

        jButton1.setText("Inventory");
        menuPanel.add(jButton1);

        jButton2.setText("Add New Item");
        menuPanel.add(jButton2);

        jButton3.setText("Register Employee");
        menuPanel.add(jButton3);

        jButton7.setText("Set Discount Rate");
        menuPanel.add(jButton7);

        jLayeredPane3.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLayeredPane3.add(jPanel1, "card2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLayeredPane3.add(jPanel2, "card3");

        javax.swing.GroupLayout managementPanelLayout = new javax.swing.GroupLayout(managementPanel);
        managementPanel.setLayout(managementPanelLayout);
        managementPanelLayout.setHorizontalGroup(
            managementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managementPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(managementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        managementPanelLayout.setVerticalGroup(
            managementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managementPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(306, Short.MAX_VALUE))
        );

        mainPanels.add(managementPanel, "card3");

        loginArea.setLayout(new java.awt.GridLayout(2, 3, 3, 3));

        usernameLabel.setText("Username");
        loginArea.add(usernameLabel);

        passwordLabel.setText("Password");
        loginArea.add(passwordLabel);
        loginArea.add(fillerLabel);
        loginArea.add(usernameField);
        loginArea.add(passwordField);

        submitButton.setText("Log In");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        loginArea.add(submitButton);

        loginMessageLabel.setFont(new java.awt.Font(".SF NS Text", 0, 24)); // NOI18N
        loginMessageLabel.setText("Not logged in.");

        logOutButton.setText("Log Out");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 903, Short.MAX_VALUE)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(loginPanelLayout.createSequentialGroup()
                    .addComponent(loginArea, javax.swing.GroupLayout.DEFAULT_SIZE, 903, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(loginMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(198, Short.MAX_VALUE))
            .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(loginPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(loginArea, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(413, Short.MAX_VALUE)))
        );

        mainPanels.add(loginPanel, "card3");

        FrameMenuPanel.setLayout(new java.awt.GridLayout(1, 0));

        registerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        registerButton.setText("REGISTER");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        FrameMenuPanel.add(registerButton);

        logInButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login.png"))); // NOI18N
        logInButton.setText("LOG IN");
        logInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInButtonActionPerformed(evt);
            }
        });
        FrameMenuPanel.add(logInButton);

        managementButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/settings.png"))); // NOI18N
        managementButton.setText("MANAGEMENT");
        managementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managementButtonActionPerformed(evt);
            }
        });
        FrameMenuPanel.add(managementButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mainPanels, javax.swing.GroupLayout.PREFERRED_SIZE, 909, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(FrameMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FrameMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(mainPanels, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoActionPerformed

    private void fruitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fruitButtonActionPerformed
        switchPanels(fruitPanel);
    }//GEN-LAST:event_fruitButtonActionPerformed

    private void appleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appleButtonActionPerformed
        jTextArea1.append(apple.toString());
        updateTotal(apple.getPrice());
    }//GEN-LAST:event_appleButtonActionPerformed

    private void cornButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cornButtonActionPerformed
        jTextArea1.append(corn.toString());
        updateTotal(corn.getPrice());
        //subTotalLabel.setText(String.format("%.2f", potato.getPrice()));
    }//GEN-LAST:event_cornButtonActionPerformed

    private void produceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produceButtonActionPerformed
        switchPanels(producePanel);
    }//GEN-LAST:event_produceButtonActionPerformed

    private void deliButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliButtonActionPerformed
        switchPanels(deliPanel);
    }//GEN-LAST:event_deliButtonActionPerformed

    private void orangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orangeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orangeButtonActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        // TODO add your handling code here:
        switchPanels2(registerPanel);
    }//GEN-LAST:event_registerButtonActionPerformed

    private void managementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managementButtonActionPerformed
        // TODO add your handling code here:
        switchPanels2(managementPanel);
    }//GEN-LAST:event_managementButtonActionPerformed

    private void potatoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potatoButtonActionPerformed
        // TODO add your handling code here:
        jTextArea1.append(potato.toString());
        updateTotal(potato.getPrice());
    }//GEN-LAST:event_potatoButtonActionPerformed

    private void broccoliButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_broccoliButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_broccoliButtonActionPerformed

    private void wholePizzaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wholePizzaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wholePizzaButtonActionPerformed

    private void bakeryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bakeryButtonActionPerformed
        switchPanels(bakeryPanel);
    }//GEN-LAST:event_bakeryButtonActionPerformed

    private void foodCourtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodCourtButtonActionPerformed
        switchPanels(foodCourtPanel);
    }//GEN-LAST:event_foodCourtButtonActionPerformed

    private void bulkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bulkButtonActionPerformed
        switchPanels(bulkPanel);
    }//GEN-LAST:event_bulkButtonActionPerformed

    private void logInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInButtonActionPerformed
        switchPanels2(loginPanel);
    }//GEN-LAST:event_logInButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        if (passwordField.getPassword().length > 0) loginMessageLabel.setText("Logged in as: " + usernameField.getText());
    }//GEN-LAST:event_submitButtonActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        loginMessageLabel.setText("Successfully logged out.");
    }//GEN-LAST:event_logOutButtonActionPerformed
    
    double subtotal=0;
    double tax=0;
    double total=0;
    Item potato = new Item("Potato","0001", 0.99,25);
    Item lettuce = new Item("Lettuce", "0002", 1.05, 39);
    Item apple = new Item("Apple","0003", 0.50, 100);
    Item corn = new Item("Corn","0004", 0.50, 100);
    //Item i = new Item("i","0005", 0.50, 100);
    //Item i = new Item("i","0006", 0.50, 100);
    //Item i = new Item("i","0007", 0.50, 100);
    //Item i = new Item("i","0008", 0.50, 100);
    //Item i = new Item("i","0009", 0.50, 100);
    /**
     * @param args the command line arguments
     */
    public void switchPanels(JPanel panel)
    {
        unscannableItemsPanels.removeAll();
        unscannableItemsPanels.add(panel);
        unscannableItemsPanels.repaint();
        unscannableItemsPanels.revalidate();
    }
    public void switchPanels2(JPanel panel)
    {
        mainPanels.removeAll();
        mainPanels.add(panel);
        mainPanels.repaint();
        mainPanels.revalidate();
    }
    public void updateTotal(double price)
    {
        subtotal = subtotal + price;
        tax = subtotal *0.0925;
        total = subtotal + tax;
        subTotalLabel.setText(String.format("%.2f", subtotal));
        taxLabel.setText(String.format("%.2f",tax));
        totalLabel.setText(String.format("%.2f",total));
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grocery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grocery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grocery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grocery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grocery().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FrameMenuPanel;
    private javax.swing.JButton almondsButton;
    private javax.swing.JButton appleButton;
    private javax.swing.JButton bagelButton;
    private javax.swing.JButton baguetteButton;
    private javax.swing.JButton bakeryButton;
    private javax.swing.JPanel bakeryPanel;
    private javax.swing.JButton bananaButton;
    private javax.swing.JButton bolognaButton;
    private javax.swing.JButton broccoliButton;
    private javax.swing.JButton bulkButton;
    private javax.swing.JPanel bulkPanel;
    private javax.swing.JButton cakeButton;
    private javax.swing.JButton candyButton;
    private javax.swing.JButton carrotButton;
    private javax.swing.JButton cashewsButton;
    private javax.swing.JButton cheddarButton;
    private javax.swing.JButton cherriesButton;
    private javax.swing.JButton churrosButton;
    private javax.swing.JButton cookiesButton;
    private javax.swing.JButton cornButton;
    private javax.swing.JButton cucumberButton;
    private javax.swing.JButton deliButton;
    private javax.swing.JPanel deliPanel;
    private javax.swing.JButton driedFruitButton;
    private javax.swing.JLabel fillerLabel;
    private javax.swing.JButton flourButton;
    private javax.swing.JButton foodCourtButton;
    private javax.swing.JPanel foodCourtPanel;
    private javax.swing.JButton fruitButton;
    private javax.swing.JPanel fruitPanel;
    private javax.swing.JButton garlicButton;
    private javax.swing.JButton goudaButton;
    private javax.swing.JButton granolaButton;
    private javax.swing.JButton grapesButton;
    private javax.swing.JButton greenBeanButton;
    private javax.swing.JButton hamButton;
    private javax.swing.JButton hotDogButton;
    private javax.swing.JButton iceCreamButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelTotal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton kiwiButton;
    private javax.swing.JButton largeDrinkButton;
    private javax.swing.JButton lettuceButton;
    private javax.swing.JButton logInButton;
    private javax.swing.JButton logOutButton;
    private javax.swing.JPanel loginArea;
    private javax.swing.JLabel loginMessageLabel;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JButton logo;
    private javax.swing.JPanel lowerMenuPanel;
    private javax.swing.JLayeredPane mainPanels;
    private javax.swing.JButton managementButton;
    private javax.swing.JPanel managementPanel;
    private javax.swing.JButton mangoButton;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JButton mozzarellaButton;
    private javax.swing.JButton muffinButton;
    private javax.swing.JButton oatsButton;
    private javax.swing.JButton onionButton;
    private javax.swing.JButton orangeButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton peanutsButton;
    private javax.swing.JButton pepperJackButton;
    private javax.swing.JButton pineappleButton;
    private javax.swing.JButton pizzaSliceButton;
    private javax.swing.JButton potatoButton;
    private javax.swing.JButton produceButton;
    private javax.swing.JPanel producePanel;
    private javax.swing.JButton registerButton;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JButton roastBeefButton;
    private javax.swing.JButton rollsButton;
    private javax.swing.JButton ryeLoafButton;
    private javax.swing.JButton saladButton;
    private javax.swing.JButton salamiButton;
    private javax.swing.JButton sandwichButton;
    private javax.swing.JButton smallDrinkButton;
    private javax.swing.JButton soupButton;
    private javax.swing.JButton sourdoughLoafButton;
    private javax.swing.JButton spinachButton;
    private javax.swing.JButton strawberriesButton;
    private javax.swing.JLabel subTotalLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JButton sugarButton;
    private javax.swing.JButton swissButton;
    private javax.swing.JLabel taxLabel;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JButton trailMixButton;
    private javax.swing.JButton turkeyButton;
    private javax.swing.JPanel unscannableItemsButtons;
    private javax.swing.JLabel unscannableItemsLabel;
    private javax.swing.JLayeredPane unscannableItemsPanels;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JButton watermelonButton;
    private javax.swing.JButton wheatLoafButton;
    private javax.swing.JButton whiteLoafButton;
    private javax.swing.JButton wholePizzaButton;
    // End of variables declaration//GEN-END:variables
}
